// <auto-generated />
namespace QuestBuild_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddClassesForStudents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddClassesForStudents));
        
        string IMigrationMetadata.Id
        {
            get { return "201504250608406_AddClassesForStudents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
